# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'Assignment' do
  use_frameworks!
  
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxOptional'
end
